# cspell:disable
name: Metadata

on:
  push:
    branches: [ main, ci ]

jobs:
  changelog-and-dependencies:
    permissions: 
      contents: write
    name: CHANGELOG and deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
      - name: Install graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Cache restore
        id: cache-restore
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: metadata-cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Rustup stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
      - name: Install cargo-deps
        if: steps.cache-restore.outputs.cache-hit != 'true'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-deps
        env:
          CARGO_TARGET_DIR: target/
      - name: Build all features
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features
        env:
          RUSTFLAGS: "-C target-feature=+avx2"
      - name: Generate deps.png
        run: cargo deps | dot -Tpng > deps.png
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "CHANGELOG.md --force deps.png --force"
          default_author: github_actions
          message: "chore: update CHANGELOG.md and deps.png" 
          push: true